### ISSUE TITLE
When modal is opening scrolls to the top of the page

### ISSUE THREAD

**Issue by romanov** [robinparisi/tingle#124]
1. Open modal
2. Page scrolls to the top.

**Comment by qmarcos** [comment]
If you manage the click with a custom function and are using a link with an href="#", maybe your link is causing this behaviour. You could prevent it on your click listener. Here is an example:

```js
var modalTrigger = document.querySelector('selector-of-your-link');
var modal = new tingle.modal();

modalTrigger.addEventListener('click', function(ev) {

    // this line invalidate the behaviour of the link 
    // that is causing scrolling to top
    ev.preventDefault(); 

    modal.setContent('<p>Hello!</p>');
    modal.open();
});
```

Hope it helps.

**Comment by St-Permiakov** [comment]
Same issue here.
For me this is caused by the wrong actions order in "close" method.

`        
document.body.classList.remove('tingle-enabled') <-- this is where position='fixed' removed
window.scrollTo(0, this._scrollPosition) <-- no scrollbar is available due to 'top: -####px', but scrollTo is called
document.body.style.top = null <-- scrollbar appears, but no scroll action is called
`

I'm going to make PR here that will fix it.
As a tmp solution you can take package out of npm and implement fix locally.
Just swap "scrollTo" and "body.style.top = null" and you might be OK.
