### ISSUE TITLE
Consider inserting modal at end of body

### ISSUE THREAD

**Issue by yomed** [robinparisi/tingle#134]
Hi, thanks for the great project!

I noticed that currently, the modal gets inserted into the DOM at the top of the body. For some use cases, this could be undesirable. For example, when Google picks up content for page descriptions, it often goes to the first text on the page. I imagine that in most cases, content in the modal text would not be considered important enough for that to be desired.

The only change needed would be on this line:
https://github.com/robinparisi/tingle/blob/4e4237a49858667cecbf570374016e66b64f9b21/dist/tingle.js#L53

I noticed that this change would also help solve another issue https://github.com/robinparisi/tingle/issues/109 (cc @emmanuelballery)

**Comment by robinparisi** [comment]
Hey @yomed,

Done here: https://github.com/robinparisi/tingle/commit/caaa6ff0b8a1a6d8286a4040d07d92f9246a26be

To be honest, since Google crawlers are using a Chrome headless, they can detect hidden content and are able to extract main content. I'm not sure tingle content can be found in meta description but if you have an example, I'm interested!

**Comment by yomed** [comment]
@robinparisi Thanks for the fix! In seems like in some cases Google ignores the meta description, and instead goes looking for text from the main content. So I was running into that with my project, where it picked up the modal text.

**Comment by robinparisi** [comment]
Ok, that's interesting, thanks for the feedback! :smiley:
