### ISSUE TITLE
Is the project still maintained?

### ISSUE THREAD

**Issue by fromaline** [robinparisi/tingle#143]
Hi, @robinparisi! Thanks for the project!
I start to use tingle and find it quite fun to work with, but it misses some accessibility features and have scrollbar bug on Windows.
I quickly fix it in my project with some dirty code, but now want to refactor my solutions and contribute them to original repo here.
The question is - should I contribute to the project or leave the fixies only on my side? Is the project still maintained?

**Comment by robinparisi** [comment]
Hi @fromaline,

If you are referring to this issue (https://github.com/robinparisi/tingle/issues/141), I'm looking for help on Windows (scrollbar management is pretty annoying since I get bugs related to it regularly but didn't manage to find a good solution for all platforms) 

Same thing for a11y as I would love to make tingle more accessible. I started working on a version 1.0 based on Rollup and ESM but haven't had time to continue yet.

**Comment by fromaline** [comment]
Yeah, I was referring to that issue, just forgot to point out explicitly :)
Thanks for clearing things out, I will try to implement my fixies 👍

**Comment by Icaras12x** [comment]
Please keep it alive ! I find it extremely intuitive and would love to keep using it on my website. It would also be amazing if you could add some different popup animations... Love from italy

**Comment by CodeWithOz** [comment]
Just gonna add that I'm about to start using it too so please keep it alive! Thanks for all the hard work! :+1:

**Comment by robinparisi** [comment]
Thanks for the feedback, I don't plan to stop it :)
