### ISSUE TITLE
ajax support

### ISSUE THREAD

**Issue by robertpmansion** [robinparisi/tingle#21]
Hi,

Could you add an ajax call functionality? Like what fancybox has, when you set a class to an <a> tag it will open a pop-up box and get the content from its href target. Thanks :)

**Comment by robinparisi** [comment]
Hi @robertpmansion ,

Sorry for the delay. Since tingle is a lightweight modal plugin, I would rather avoid making the base more complex by adding functionalities like ajax since this behavior can be easily created outside the modal. For example, you can create a common method to get content via ajax from href and instantiate new tingle with the recovered content.

**Comment by mscreenie** [comment]
Agree. I like to think leaving to to the developer is a better way rather than adding a rigid form of ajax support.
