### ISSUE TITLE
Sass SCSS version

### ISSUE THREAD

**Issue by microcipcip** [robinparisi/tingle#25]
Are you interested in adding a Sass version to allow quick styling through vars? I can send a pull request, obviously if you're interested.

**Comment by robinparisi** [comment]
Hi,

Thanks a lot for the proposal but to be honest, I think maintaining multiple CSS versions on the long term is not very convenient (because if we add Sass, why not add Less?). As you can see, I want to keep tingle simple and easy to maintain. Besides, for a plugin, I think it's better to provide a small CSS base and let people adapt it to their own workflows.

**Comment by microcipcip** [comment]
Ok, makes sense, thanks for the reply :)
