### ISSUE TITLE
<form> tag disappear

### ISSUE THREAD

**Issue by jnkindi** [robinparisi/tingle#58]
The form tag disappear when pop up shows.

![codes](https://user-images.githubusercontent.com/14198719/27919599-6728a134-6272-11e7-9c08-f02f02cd11d5.png)
![view](https://user-images.githubusercontent.com/14198719/27919597-663aad3a-6272-11e7-8163-b6e276301d66.png)

its opening and closing dont show up in browser.

**Comment by ginsterbusch** [comment]
hm .. could it be because you are setting spaces, where no spaces should be? ie. right before and after the attributes, eg. `class = ".."` instead of correctly `class=".."`?

I've set up tingle together with a (self-built!) bootstrap-based WP Theme just this morning, and so far, it works flawlessly.

cu, w0lf.

**Comment by robinparisi** [comment]
Hi @jnkindi,

This seems to be due to a badly closed tag (div).

**Comment by jnkindi** [comment]
Ohh @robinparisi @ginsterbusch
Thanks it was due to the (div) not closed correctly
